
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.shmslibrary_module.ArrayOfWeatherItem;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISHMSService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.shmslibrary_module.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface ISHMSService {


    /**
     * 
     * @param start
     * @param end
     * @return
     *     returns org.datacontract.schemas._2004._07.shmslibrary_module.ArrayOfWeatherItem
     */
    @WebMethod(operationName = "GetWeatherData", action = "http://tempuri.org/ISHMSService/GetWeatherData")
    @WebResult(name = "GetWeatherDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWeatherData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWeatherData")
    @ResponseWrapper(localName = "GetWeatherDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWeatherDataResponse")
    public ArrayOfWeatherItem getWeatherData(
        @WebParam(name = "start", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar start,
        @WebParam(name = "end", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar end);

    /**
     * 
     * @param file
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SubmitWIMS", action = "http://tempuri.org/ISHMSService/SubmitWIMS")
    @WebResult(name = "SubmitWIMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SubmitWIMS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SubmitWIMS")
    @ResponseWrapper(localName = "SubmitWIMSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SubmitWIMSResponse")
    public Boolean submitWIMS(
        @WebParam(name = "file", targetNamespace = "http://tempuri.org/")
        byte[] file);

}
