
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SHMSService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/home/cshao/self-learning-space/09SHMTest/SHMSService.wsdl")
public class SHMSService
    extends Service
{

    private final static URL SHMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHMSSERVICE_EXCEPTION;
    private final static QName SHMSSERVICE_QNAME = new QName("http://tempuri.org/", "SHMSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/cshao/self-learning-space/09SHMTest/SHMSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHMSSERVICE_WSDL_LOCATION = url;
        SHMSSERVICE_EXCEPTION = e;
    }

    public SHMSService() {
        super(__getWsdlLocation(), SHMSSERVICE_QNAME);
    }

    public SHMSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHMSSERVICE_QNAME, features);
    }

    public SHMSService(URL wsdlLocation) {
        super(wsdlLocation, SHMSSERVICE_QNAME);
    }

    public SHMSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHMSSERVICE_QNAME, features);
    }

    public SHMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SHMSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISHMSService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ISHMSService")
    public ISHMSService getBasicHttpsBindingISHMSService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpsBinding_ISHMSService"), ISHMSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISHMSService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ISHMSService")
    public ISHMSService getBasicHttpsBindingISHMSService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpsBinding_ISHMSService"), ISHMSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHMSSERVICE_EXCEPTION!= null) {
            throw SHMSSERVICE_EXCEPTION;
        }
        return SHMSSERVICE_WSDL_LOCATION;
    }

}
